// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcPj1yKGG5oEtCKJdpEwEL_kjOKCloDr0',
    appId: '1:582209082221:web:7adbd4e970e2657dda0064',
    messagingSenderId: '582209082221',
    projectId: 'nutriscope-f2b10',
    authDomain: 'nutriscope-f2b10.firebaseapp.com',
    storageBucket: 'nutriscope-f2b10.firebasestorage.app',
    measurementId: 'G-WJT58CSZYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8foc4PYezMkoetKT6DOS-oSHzZBojRI',
    appId: '1:582209082221:android:0afcc5c3a17aef04da0064',
    messagingSenderId: '582209082221',
    projectId: 'nutriscope-f2b10',
    storageBucket: 'nutriscope-f2b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg0NLsK30kOPIxxh9BJylIGEvbW_RjycE',
    appId: '1:582209082221:ios:8c69d2ae134d80ccda0064',
    messagingSenderId: '582209082221',
    projectId: 'nutriscope-f2b10',
    storageBucket: 'nutriscope-f2b10.firebasestorage.app',
    iosClientId: '582209082221-r7d0rnblgopd6a43ra6a1n5svchbf8b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.consumeWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg0NLsK30kOPIxxh9BJylIGEvbW_RjycE',
    appId: '1:582209082221:ios:8c69d2ae134d80ccda0064',
    messagingSenderId: '582209082221',
    projectId: 'nutriscope-f2b10',
    storageBucket: 'nutriscope-f2b10.firebasestorage.app',
    iosClientId: '582209082221-r7d0rnblgopd6a43ra6a1n5svchbf8b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.consumeWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcPj1yKGG5oEtCKJdpEwEL_kjOKCloDr0',
    appId: '1:582209082221:web:60a17d9fbbbb43c0da0064',
    messagingSenderId: '582209082221',
    projectId: 'nutriscope-f2b10',
    authDomain: 'nutriscope-f2b10.firebaseapp.com',
    storageBucket: 'nutriscope-f2b10.firebasestorage.app',
    measurementId: 'G-TDYBTBRTKQ',
  );
}
